### ISSUE TITLE
simply doesn't use the config correctly

### ISSUE THREAD

**Issue by Rod0fDiscord** [Ryah/SDV-Rebind#2]
i do as follows:
1. run Control Panel.exe
2. turn on ac and bind it
3. save
4. close control panel
5. open Rebind.exe
6. see a popup that says i haven't bound my ac.
![image](https://github.com/Ryah/SDV-Rebind/assets/121453395/45c2fd99-3cd7-4c76-acdc-185ba5972792)

**Comment by Itz-Cass** [comment]
i've been getting the same issue, trying to find a way to fix it somehow lol

**Comment by Ryah** [comment]
fixed with https://github.com/Ryah/SDV-Rebind/pull/3 and included in the latest release

https://github.com/Ryah/SDV-Rebind/releases/tag/v2.0.2
